Repository molgorithm/molgorithm2, pull requests merged in 2021-06, with the labels that each got.

#1 조명희: BOJ 1000 A+B
  myoung/1000/README.md
  myoung/1000/boj1000.py
Labels: python

#4 윤승환: BOJ 1000 A+B
  seunghwan/1000/README.md
  seunghwan/1000/boj1000.java
Labels: java

#6 박다솔: BOJ 1000 A+B
  Park-Dasol/1000/README.md
  Park-Dasol/1000/boj1000.py
Labels: python

#8 김하늘 : BOJ 1000 A+B
  Kim-Ha-Neul/1000/README.md
  Kim-Ha-Neul/1000/boj1000.java
Labels: python

#11 myoung boj 1001 A-B
  myoung/1001/.idea/.gitignore
  myoung/1001/.idea/1001.iml
  myoung/1001/.idea/inspectionProfiles/Project_Default.xml
  myoung/1001/.idea/inspectionProfiles/profiles_settings.xml
  myoung/1001/.idea/misc.xml
  myoung/1001/.idea/modules.xml
  myoung/1001/.idea/vcs.xml
  myoung/1001/README.md
  myoung/1001/boj1001.py
Labels: python

#16 ysh BOJ 20061 모노미노도미노2
  seunghwan/19236/G2_19236청소년상어_2.java
  seunghwan/19236/README.md
  seunghwan/20061/G2_20061모노미노도미노2_2.java
  seunghwan/20061/README.md
Labels: java

#13 ysh BOJ 19236 청소년 상어
  seunghwan/19236/G2_19236청소년상어_2.java
  seunghwan/19236/README.md
Labels: java

#18 docs: commit message에 문제 이름 추가
  README.md
Labels: documentation

#44 Jonghui programmers 64065 튜플
  jonghui/programers_64065/README.md.md
  jonghui/programers_64065/programers_64065.py
Labels: python

#41 Jonghui programmers 64061 크레인 인형뽑기
  jonghui/programers_64061/README.md.md
  jonghui/programers_64061/programers_64061.py
Labels: python

#36 Park-Dasol Programmers 64061 크레인 인형 뽑기
  Park-Dasol/64061/README.md
  Park-Dasol/64061/programmers64061.py
Labels: python

#57 ysh programmers 67256 키패드 누르기
  seunghwan/programmers/67256/P67256키패드누르기.java
  seunghwan/programmers/67256/README.md
Labels: java

#49 myoung programmers 67256 키패드 누르기
  myoung/programmers/67256/README.md
  myoung/programmers/67256/programmers_67256.py
Labels: python
